/* Generated By:JJTree&JavaCC: Do not edit this line. ExampleParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAME = 7;
  /** RegularExpression Id. */
  int CHILDREN = 8;
  /** RegularExpression Id. */
  int CONTENT = 9;
  /** RegularExpression Id. */
  int CODE = 10;
  /** RegularExpression Id. */
  int O_OPENBRACE = 11;
  /** RegularExpression Id. */
  int O_CLOSEBRACE = 12;
  /** RegularExpression Id. */
  int O_OPENBRACKET = 13;
  /** RegularExpression Id. */
  int O_CLOSEBRACKET = 14;
  /** RegularExpression Id. */
  int O_COMMA = 15;
  /** RegularExpression Id. */
  int O_COLON = 16;
  /** RegularExpression Id. */
  int O_DOT = 17;
  /** RegularExpression Id. */
  int O_PLUS = 18;
  /** RegularExpression Id. */
  int O_MINUS = 19;
  /** RegularExpression Id. */
  int O_QUOTATIONMARKS = 20;
  /** RegularExpression Id. */
  int O_OPENPARENTHESIS = 21;
  /** RegularExpression Id. */
  int O_CLOSEPARENTHESIS = 22;
  /** RegularExpression Id. */
  int O_SLASH = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int LETTER = 25;
  /** RegularExpression Id. */
  int SPACE = 26;
  /** RegularExpression Id. */
  int STRING_NAME = 27;
  /** RegularExpression Id. */
  int STRING_CONTENT = 28;
  /** RegularExpression Id. */
  int STRING_CODE = 29;
  /** RegularExpression Id. */
  int QUOTED_STRING = 30;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<NAME>",
    "<CHILDREN>",
    "<CONTENT>",
    "<CODE>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\"/\"",
    "<DIGIT>",
    "<LETTER>",
    "<SPACE>",
    "<STRING_NAME>",
    "<STRING_CONTENT>",
    "<STRING_CODE>",
    "<QUOTED_STRING>",
    "<SINGLE_QUOTED_STRING>",
  };

}
