/* Generated By:JavaCC: Do not edit this line. ExampleParserTreeConstants.java Version 6.0_1 */
public interface ExampleParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTNAME = 1;
  public int JJTCONTENT = 2;
  public int JJTCODE = 3;
  public int JJTCHILDREN = 4;


  public String[] jjtNodeName = {
    "start",
    "NAME",
    "CONTENT",
    "CODE",
    "CHILDREN",
  };
}
/* JavaCC - OriginalChecksum=45f0d9696cef2b44069ad71a128a6229 (do not edit this line) */
