/* Generated By:JavaCC: Do not edit this line. ExampleParserTreeConstants.java Version 5.0 */
public interface ExampleParserTreeConstants
{
  public int JJTPILA = 0;
  public int JJTNAME = 1;
  public int JJTCONTENT = 2;
  public int JJTCODE = 3;
  public int JJTCHILDREN = 4;


  public String[] jjtNodeName = {
    "pila",
    "NAME",
    "CONTENT",
    "CODE",
    "CHILDREN",
  };
}
/* JavaCC - OriginalChecksum=87d344639a20cc3c862c95ca2aa70972 (do not edit this line) */
