/* Generated By:JavaCC: Do not edit this line. ExampleParserTreeConstants.java Version 5.0 */
public interface ExampleParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTNAME = 1;
  public int JJTCONTENT = 2;
  public int JJTCODE = 3;
  public int JJTCHILDREN = 4;


  public String[] jjtNodeName = {
    "start",
    "NAME",
    "CONTENT",
    "CODE",
    "CHILDREN",
  };
}
/* JavaCC - OriginalChecksum=870da39648b48c87edd2615cc13c13d3 (do not edit this line) */
