/* Generated By:JavaCC: Do not edit this line. ExampleParserTreeConstants.java Version 5.0 */
public interface ExampleParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTNODE = 1;


  public String[] jjtNodeName = {
    "start",
    "NODE",
  };
}
/* JavaCC - OriginalChecksum=c12a2cd5239ba4665022e7b83d0f8cf0 (do not edit this line) */
