import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SimpleNode implements Node {

	protected Node parent;
	protected Node[] children;
	protected int id; 
	protected Object value;
	protected Object name;
	protected Object content;
	protected Object code;
	protected ExampleParser parser;
	protected  static Boolean foundmain = false;


	public SimpleNode(int i) {
		id = i;
	}

	public SimpleNode(ExampleParser p, int i) {
		this(i);
		parser = p;
	}

	public void jjtOpen() {
	}

	public void jjtClose() {
	}

	public void jjtSetParent(Node n) { parent = n; }
	public Node jjtGetParent() { return parent; }

	public void jjtAddChild(Node n, int i) {
		if (children == null) {
			children = new Node[i + 1];
		} else if (i >= children.length) {
			Node c[] = new Node[i + 1];
			System.arraycopy(children, 0, c, 0, children.length);
			children = c;
		}
		children[i] = n;
	}

	public Node jjtGetChild(int i) {
		return children[i];
	}

	public int jjtGetNumChildren() {
		return (children == null) ? 0 : children.length;
	}

	public void jjtSetValue(Object value) { this.value = value; }
	public Object jjtGetValue() { return value; }

	/* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

	public String toString() { return ExampleParserTreeConstants.jjtNodeName[id]; }
	public String toString(String prefix) { return prefix + toString(); }

	/* Override this method if you want to customize how the node dumps
     out its children. */

	public void dump(String prefix) {
		System.out.println(toString(prefix) + name);
		if (children != null) {
			for (int i = 0; i < children.length; ++i) {
				SimpleNode n = (SimpleNode)children[i];
				if (n != null) {
					//	System.out.println(value);
					n.dump(prefix + " ");
				}
			}
		}
	}
	public void printstuff(String prefix){
		//System.out.println(value);
		PrintWriter writer = null;
		try {
			writer = new PrintWriter("dotfile.dot", "UTF-8");
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		writer.println("digraph graphname{");
		//drawtherest(writer,prefix,prefix);
		ArrayList<String> order = new ArrayList<String>();
		filter(writer,prefix, order);
		writer.println("}");
		writer.close();
	}

	private void drawtherest(PrintWriter writer,String prefix,String parent) {
		// TODO Auto-generated method stub
		//writer.println(";");
		/*
	if (children != null) {
	      for (int i = 0; i < children.length; ++i) {
	        SimpleNode n = (SimpleNode)children[i];
	        if (n != null) {
	        writer.println(n.jjtGetParent() + "--" + n.jjtGetValue());
	        n.drawtherest(writer, prefix);
	        }
	      }
	    }
		 */
		String temp;
		if (this.children != null) {
			for (int i = 0; i < this.children.length; ++i) {
				SimpleNode n = (SimpleNode)this.children[i];
				SimpleNode p = (SimpleNode)n.parent;
				writer.println(p.name + " -- " + n.name + ";");
				if(n != null)
					//  writer.print("gotcha");

					n.drawtherest(writer, prefix,prefix);
			}
		}
	}

	public void filter(PrintWriter writer,String string, ArrayList<String> order) {
		// TODO Auto-generated method stub
		String temp;
		if (this.children != null) {
			for (int i = 0; i < this.children.length; ++i) {
				SimpleNode n = (SimpleNode)this.children[i];
				SimpleNode p = (SimpleNode)n.parent;
				if(foundmain)
				{	
					if(n.name.equals("\"Block\""))
						analyzeblock(n);

				}
				if(n.name!=null){
					if(n.name.equals("\"Method\"")){
						if(n.content.equals("\"main\"")){ //para o caso do main
							SimpleNode c = (SimpleNode)n.children[0];
							foundmain = true;

							if(n.children.length == 2) //estamos a contar que exista sempre Block
								writer.println(")");
							else {

								for (int j = 1; j < n.children.length - 1; j++) { 
									String mainSentence = "\"" + removeQuotationMarks(c.content) + " " + removeQuotationMarks(n.content) +"(";
									c = (SimpleNode)n.children[j];
									SimpleNode cc = (SimpleNode)c.children[0];

									if(cc.name.equals("\"TypeReference\"")) //se for typereference nao tem mais filhos
										mainSentence += removeQuotationMarks(cc.content) + " " + removeQuotationMarks(c.content);

									if(cc.name.equals("\"ArrayTypeReference\"")){ //se for arraytypereference tem mais um filho
										SimpleNode ccc = (SimpleNode)cc.children[0];
										mainSentence += removeQuotationMarks(ccc.content) + "[] " + removeQuotationMarks(c.content);
									}

									if(j == n.children.length - 2){
										mainSentence += ")\"";
										order.add(mainSentence);
										writer.print(order.get(0));
										break;
									}
									else {
										mainSentence += ", ";
									}
								}			
							}
							SimpleNode block = (SimpleNode)n.children[n.children.length-1];
							for(int k = 0; k < block.children.length; k++)
							{
								c = (SimpleNode)block.children[k];
								if(c.name.equals("\"LocalVariable\""))
								{
									String variable = "";
									SimpleNode cc = (SimpleNode)c.children[0];
									if(cc.name.equals("\"TypeReference\"")) //se for typereference nao tem mais filhos
										variable += "\"" + removeQuotationMarks(cc.content) + " " + removeQuotationMarks(c.content);

									else if(cc.name.equals("\"ArrayTypeReference\"")){ //se for arraytypereference tem mais um filho
										SimpleNode ccc = (SimpleNode)cc.children[0];
										variable += "\"" + removeQuotationMarks(ccc.content) + "[] " + removeQuotationMarks(c.content);
									}

									if(c.children.length == 1){
										variable += (";");
									}
									else{									//rever este else mais tarde
										cc = (SimpleNode)c.children[1];
										if(cc.name.equals("\"Literal\"")){
											variable += " = " + removeQuotationMarks(cc.content) + ";" + "\"";
										}
									}
									writer.print(" -> " + variable);
									order.add(variable);
								}
								if(c.name.equals("\"If\"")) 
								{
									//CONDICAO
									String ifCondition = null;
									SimpleNode cc = (SimpleNode)c.children[0];
									if(cc.name.equals("\"BinaryOperator\""))	//IF DO TIPO if(a operador b)
									{
										String binaryOperator = (String) cc.content;
										String compare1 = null;
										String compare2 = null;
										SimpleNode ccc = (SimpleNode)cc.children[1];
										if(ccc.name.equals("\"VariableRead\""))
										{
											SimpleNode cccc = (SimpleNode)ccc.children[1];
											compare1 = (String) cccc.content;
										}	
										else if(ccc.name.equals("\"Literal\""))
										{
											compare1 = (String) ccc.content;
										}
										ccc = (SimpleNode)cc.children[2];
										if(ccc.name.equals("\"VariableRead\""))
										{
											SimpleNode cccc = (SimpleNode)ccc.children[1];
											compare2 = (String) cccc.content;
										}	
										else if(ccc.name.equals("\"Literal\""))
										{
											compare2 = (String) ccc.content;
										}
										ifCondition = "\"If(" + removeQuotationMarks(compare1) + removeQuotationMarks(binaryOperator) + removeQuotationMarks(compare2) + ")\"";	
										writer.println(" -> " + ifCondition);
									}
									//CONDICIONADOS

									cc = (SimpleNode)c.children[1];				//CONDICIONADO TRUE
									String lastLine = "";			//*ultima linha para ser adicionado ao arraylist*
									writer.print(ifCondition);
									//for(int l = 0; l < cc.children.length; l++)		//*nao sei se o for se mete aqui*
									//{
										if(cc.name.equals("\"Invocation\""))
										{
											SimpleNode ccc = (SimpleNode)cc.children[2];
											if(ccc.name.equals("\"ExecutableReference\""))
											{
												if(ccc.content.equals("\"println\""))
												{
													ccc = (SimpleNode)cc.children[3];
													lastLine = " -> " + "\"System.out.println(" + "\\" + "\"" + removeQuotationMarks(removeQuotationMarks(ccc.content))+ "\\" + "\"" + ");" + "\"" + "[label=\"true\"]";
													writer.println(lastLine);
													//writer.print(lastLine);
												}
											}
										}
										//if(l == (cc.children.length - 1)){
										//	writer.println("[label=\"true\"]");
										//}
									//}

									if(c.children.length > 1)
									{
										cc = (SimpleNode)c.children[2];			//CONDICIONADO FALSE(caso exista)
										if(cc.name.equals("\"Invocation\""))
										{
											SimpleNode ccc = (SimpleNode)cc.children[2];
											if(ccc.name.equals("\"ExecutableReference\""))
											{
												if(ccc.content.equals("\"println\""))
												{
													ccc = (SimpleNode)cc.children[3];
													writer.println(ifCondition + " -> " + "\"System.out.println(" + "\\" + "\"" + removeQuotationMarks(removeQuotationMarks(ccc.content))+ "\\" + "\"" + ");" + "\"" + "[label=\"false\"]");
												}
											}
										}
									}			
								}
							}
						}
					}
				}
				//System.out.println(n.name);
				if(n != null)
					//  writer.print("gotcha");

					n.filter(writer, string, order);
			}
		}

	}

	String removeQuotationMarks(Object content2)
	{
		String operation1 = ((String) content2).substring(1, ((String) content2).length() - 1);
		return operation1;
	}

	private void analyzeblock(SimpleNode n) {
		// TODO Auto-generated method stub

		if(n.children !=null){
			for(int i=0;i< n.children.length; ++i) {
				SimpleNode e = (SimpleNode)n.children[i];
				SimpleNode p = (SimpleNode)e.parent;
				System.out.println(e.name);
				e.analyzeblock(e);
			}
		}
	}
}

/* JavaCC - OriginalChecksum=dc9708b1c46ec8e86a717c9e8819eba5 (do not edit this line) */
