/* Generated By:JavaCC: Do not edit this line. ExampleParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExampleParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAME = 5;
  /** RegularExpression Id. */
  int CHILDREN = 6;
  /** RegularExpression Id. */
  int CONTENT = 7;
  /** RegularExpression Id. */
  int CODE = 8;
  /** RegularExpression Id. */
  int STRING_NAME_CONTENT = 9;
  /** RegularExpression Id. */
  int STRING_CODE = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NAME>",
    "<CHILDREN>",
    "<CONTENT>",
    "<CODE>",
    "<STRING_NAME_CONTENT>",
    "<STRING_CODE>",
    "\"{\"",
    "\"[\"",
    "\"]\"",
    "\"}\"",
  };

}
